"""add_ingestion_jobs

Revision ID: 467c2a8d3778
Revises: 4a79f87df16e
Create Date: 2026-02-28 16:59:20.239877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.base import UUIDType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '467c2a8d3778'
down_revision: Union[str, None] = '4a79f87df16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('venue_id', UUIDType(), nullable=False),
    sa.Column('blob_key', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('floor_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('zone_count', sa.Integer(), nullable=True),
    sa.Column('connection_count', sa.Integer(), nullable=True),
    sa.Column('perch_point_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_jobs_customer_id'), 'ingestion_jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_id'), 'ingestion_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_jobs_venue_id'), 'ingestion_jobs', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingestion_jobs_venue_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_id'), table_name='ingestion_jobs')
    op.drop_index(op.f('ix_ingestion_jobs_customer_id'), table_name='ingestion_jobs')
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
