"""initial schema

Revision ID: 4a79f87df16e
Revises: 
Create Date: 2026-02-28 15:22:30.729416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.database.base import UUIDType
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '4a79f87df16e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('max_kits', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_table('kits',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('config', sa.String(), nullable=False),
    sa.Column('tier_composition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('charger_serial', sa.String(), nullable=True),
    sa.Column('case_model', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cloud_registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kits_customer_id'), 'kits', ['customer_id'], unique=False)
    op.create_index(op.f('ix_kits_id'), 'kits', ['id'], unique=False)
    op.create_index(op.f('ix_kits_serial'), 'kits', ['serial'], unique=True)
    op.create_table('principals',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('codename', sa.String(), nullable=False),
    sa.Column('ble_beacon_id', sa.String(), nullable=True),
    sa.Column('operation_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_principals_customer_id'), 'principals', ['customer_id'], unique=False)
    op.create_index(op.f('ix_principals_id'), 'principals', ['id'], unique=False)
    op.create_table('protection_agents',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('callsign', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protection_agents_customer_id'), 'protection_agents', ['customer_id'], unique=False)
    op.create_index(op.f('ix_protection_agents_id'), 'protection_agents', ['id'], unique=False)
    op.create_table('venues',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('floor_plan_source', sa.String(), nullable=True),
    sa.Column('floor_plan_blob_key', sa.String(), nullable=True),
    sa.Column('venue_model_blob_key', sa.String(), nullable=True),
    sa.Column('deployment_count', sa.Integer(), nullable=False),
    sa.Column('avg_deploy_time_s', sa.Float(), nullable=True),
    sa.Column('last_operated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_customer_id'), 'venues', ['customer_id'], unique=False)
    op.create_index(op.f('ix_venues_id'), 'venues', ['id'], unique=False)
    op.create_table('workstations',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hardware_serial', sa.String(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('registered_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_serial')
    )
    op.create_index(op.f('ix_workstations_customer_id'), 'workstations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_workstations_id'), 'workstations', ['id'], unique=False)
    op.create_table('drones',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('kit_id', UUIDType(), nullable=False),
    sa.Column('serial', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('callsign', sa.String(), nullable=True),
    sa.Column('hardware_class', sa.String(), nullable=True),
    sa.Column('spine_array_condition', sa.String(), nullable=True),
    sa.Column('suction_pump_condition', sa.String(), nullable=True),
    sa.Column('landing_gear_condition', sa.String(), nullable=True),
    sa.Column('total_flight_hours', sa.Float(), nullable=True),
    sa.Column('total_perch_hours', sa.Float(), nullable=True),
    sa.Column('total_attachments', sa.Integer(), nullable=True),
    sa.Column('attachment_success_rate', sa.Float(), nullable=True),
    sa.Column('battery_cycles', sa.Integer(), nullable=True),
    sa.Column('battery_health_pct', sa.Float(), nullable=True),
    sa.Column('surface_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reliability_score', sa.Float(), nullable=True),
    sa.Column('last_deployed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_maintained_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['kit_id'], ['kits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_customer_id'), 'drones', ['customer_id'], unique=False)
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.create_index(op.f('ix_drones_kit_id'), 'drones', ['kit_id'], unique=False)
    op.create_index(op.f('ix_drones_serial'), 'drones', ['serial'], unique=True)
    op.create_table('operations',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('venue_id', UUIDType(), nullable=False),
    sa.Column('principal_id', UUIDType(), nullable=True),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('assigned_kit_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('planned_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actual_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('actual_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('drone_count_tier1', sa.Integer(), nullable=True),
    sa.Column('drone_count_tier2', sa.Integer(), nullable=True),
    sa.Column('deploy_time_s', sa.Float(), nullable=True),
    sa.Column('total_repositions', sa.Integer(), nullable=True),
    sa.Column('total_alerts', sa.Integer(), nullable=True),
    sa.Column('alert_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_score_avg', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('briefing_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('post_op_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_customer_id'), 'operations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_operations_id'), 'operations', ['id'], unique=False)
    op.create_index(op.f('ix_operations_principal_id'), 'operations', ['principal_id'], unique=False)
    op.create_index(op.f('ix_operations_venue_id'), 'operations', ['venue_id'], unique=False)
    op.create_table('sync_events',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('workstation_id', UUIDType(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entity_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cloud_version_before', sa.Integer(), nullable=True),
    sa.Column('cloud_version_after', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_events_customer_id'), 'sync_events', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sync_events_id'), 'sync_events', ['id'], unique=False)
    op.create_index(op.f('ix_sync_events_workstation_id'), 'sync_events', ['workstation_id'], unique=False)
    op.create_table('venue_zones',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('venue_id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=True),
    sa.Column('tier_requirement', sa.String(), nullable=True),
    sa.Column('floor_level', sa.Integer(), nullable=True),
    sa.Column('polygon_json', sa.Text(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('ceiling_height_m', sa.Float(), nullable=True),
    sa.Column('area_sq_m', sa.Float(), nullable=True),
    sa.Column('coverage_priority', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venue_zones_customer_id'), 'venue_zones', ['customer_id'], unique=False)
    op.create_index(op.f('ix_venue_zones_id'), 'venue_zones', ['id'], unique=False)
    op.create_index(op.f('ix_venue_zones_venue_id'), 'venue_zones', ['venue_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('operation_id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('drone_tier', sa.String(), nullable=True),
    sa.Column('zone_id', UUIDType(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detection_data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('snapshot_blob_key', sa.String(), nullable=True),
    sa.Column('operator_validated', sa.Integer(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('escalated', sa.Integer(), nullable=True),
    sa.Column('forwarded_to_agents', sa.Integer(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['venue_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_customer_id'), 'alerts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_operation_id'), 'alerts', ['operation_id'], unique=False)
    op.create_table('perch_points',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('venue_id', UUIDType(), nullable=False),
    sa.Column('zone_id', UUIDType(), nullable=True),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('position_json', sa.Text(), nullable=True),
    sa.Column('wall_normal_json', sa.Text(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('surface_class', sa.String(), nullable=True),
    sa.Column('surface_orientation', sa.String(), nullable=True),
    sa.Column('attachment_method', sa.String(), nullable=True),
    sa.Column('tier_required', sa.String(), nullable=True),
    sa.Column('spine_confidence', sa.Float(), nullable=True),
    sa.Column('spine_wet_confidence', sa.Float(), nullable=True),
    sa.Column('suction_confidence', sa.Float(), nullable=True),
    sa.Column('landing_gear_viable', sa.Integer(), nullable=True),
    sa.Column('landing_surface_width_mm', sa.Float(), nullable=True),
    sa.Column('coverage_value', sa.Float(), nullable=True),
    sa.Column('mesh_quality', sa.Float(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('avg_hold_duration_s', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['venue_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perch_points_customer_id'), 'perch_points', ['customer_id'], unique=False)
    op.create_index(op.f('ix_perch_points_id'), 'perch_points', ['id'], unique=False)
    op.create_index(op.f('ix_perch_points_venue_id'), 'perch_points', ['venue_id'], unique=False)
    op.create_index(op.f('ix_perch_points_zone_id'), 'perch_points', ['zone_id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('operation_id', UUIDType(), nullable=True),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('wind_speed_m_s', sa.Float(), nullable=True),
    sa.Column('wind_heading_deg', sa.Float(), nullable=True),
    sa.Column('gust_speed_m_s', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.String(), nullable=True),
    sa.Column('visibility_m', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('observed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_customer_id'), 'weather_observations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_operation_id'), 'weather_observations', ['operation_id'], unique=False)
    op.create_table('wm_nodes',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decay_weight', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('venue_id', UUIDType(), nullable=True),
    sa.Column('operation_id', UUIDType(), nullable=True),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('venue_type', sa.String(), nullable=True),
    sa.Column('abstraction_level', sa.String(), nullable=False),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reinforced', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wm_nodes_customer_id'), 'wm_nodes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_wm_nodes_id'), 'wm_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_wm_nodes_venue_id'), 'wm_nodes', ['venue_id'], unique=False)
    op.create_table('zone_connections',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('venue_id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('from_zone_id', UUIDType(), nullable=False),
    sa.Column('to_zone_id', UUIDType(), nullable=False),
    sa.Column('connection_type', sa.String(), nullable=True),
    sa.Column('position_json', sa.Text(), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('is_accessible', sa.Integer(), nullable=True),
    sa.Column('last_verified_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['from_zone_id'], ['venue_zones.id'], ),
    sa.ForeignKeyConstraint(['to_zone_id'], ['venue_zones.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zone_connections_customer_id'), 'zone_connections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_zone_connections_id'), 'zone_connections', ['id'], unique=False)
    op.create_index(op.f('ix_zone_connections_venue_id'), 'zone_connections', ['venue_id'], unique=False)
    op.create_table('surface_assessments',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('perch_point_id', UUIDType(), nullable=False),
    sa.Column('operation_id', UUIDType(), nullable=True),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('drone_id', sa.String(), nullable=True),
    sa.Column('drone_tier', sa.String(), nullable=True),
    sa.Column('surface_class_predicted', sa.String(), nullable=True),
    sa.Column('surface_class_actual', sa.String(), nullable=True),
    sa.Column('surface_orientation', sa.String(), nullable=True),
    sa.Column('tof_roughness', sa.Float(), nullable=True),
    sa.Column('weather_conditions', sa.String(), nullable=True),
    sa.Column('spine_engaged', sa.Integer(), nullable=True),
    sa.Column('suction_engaged', sa.Integer(), nullable=True),
    sa.Column('landing_gear_used', sa.Integer(), nullable=True),
    sa.Column('hold_duration_s', sa.Float(), nullable=True),
    sa.Column('failure_mode', sa.String(), nullable=True),
    sa.Column('approach_image_blob_key', sa.String(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('assessed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ),
    sa.ForeignKeyConstraint(['perch_point_id'], ['perch_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surface_assessments_customer_id'), 'surface_assessments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_surface_assessments_id'), 'surface_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_surface_assessments_operation_id'), 'surface_assessments', ['operation_id'], unique=False)
    op.create_index(op.f('ix_surface_assessments_perch_point_id'), 'surface_assessments', ['perch_point_id'], unique=False)
    op.create_table('wm_edges',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('source_workstation_id', UUIDType(), nullable=True),
    sa.Column('from_node', UUIDType(), nullable=False),
    sa.Column('to_node', UUIDType(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('mechanism', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('observations', sa.Integer(), nullable=True),
    sa.Column('abstraction_level', sa.String(), nullable=True),
    sa.Column('cloud_version', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['from_node'], ['wm_nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node'], ['wm_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wm_edges_customer_id'), 'wm_edges', ['customer_id'], unique=False)
    op.create_index(op.f('ix_wm_edges_from_node'), 'wm_edges', ['from_node'], unique=False)
    op.create_index(op.f('ix_wm_edges_id'), 'wm_edges', ['id'], unique=False)
    op.create_index(op.f('ix_wm_edges_to_node'), 'wm_edges', ['to_node'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wm_edges_to_node'), table_name='wm_edges')
    op.drop_index(op.f('ix_wm_edges_id'), table_name='wm_edges')
    op.drop_index(op.f('ix_wm_edges_from_node'), table_name='wm_edges')
    op.drop_index(op.f('ix_wm_edges_customer_id'), table_name='wm_edges')
    op.drop_table('wm_edges')
    op.drop_index(op.f('ix_surface_assessments_perch_point_id'), table_name='surface_assessments')
    op.drop_index(op.f('ix_surface_assessments_operation_id'), table_name='surface_assessments')
    op.drop_index(op.f('ix_surface_assessments_id'), table_name='surface_assessments')
    op.drop_index(op.f('ix_surface_assessments_customer_id'), table_name='surface_assessments')
    op.drop_table('surface_assessments')
    op.drop_index(op.f('ix_zone_connections_venue_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_id'), table_name='zone_connections')
    op.drop_index(op.f('ix_zone_connections_customer_id'), table_name='zone_connections')
    op.drop_table('zone_connections')
    op.drop_index(op.f('ix_wm_nodes_venue_id'), table_name='wm_nodes')
    op.drop_index(op.f('ix_wm_nodes_id'), table_name='wm_nodes')
    op.drop_index(op.f('ix_wm_nodes_customer_id'), table_name='wm_nodes')
    op.drop_table('wm_nodes')
    op.drop_index(op.f('ix_weather_observations_operation_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_customer_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_perch_points_zone_id'), table_name='perch_points')
    op.drop_index(op.f('ix_perch_points_venue_id'), table_name='perch_points')
    op.drop_index(op.f('ix_perch_points_id'), table_name='perch_points')
    op.drop_index(op.f('ix_perch_points_customer_id'), table_name='perch_points')
    op.drop_table('perch_points')
    op.drop_index(op.f('ix_alerts_operation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_customer_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_venue_zones_venue_id'), table_name='venue_zones')
    op.drop_index(op.f('ix_venue_zones_id'), table_name='venue_zones')
    op.drop_index(op.f('ix_venue_zones_customer_id'), table_name='venue_zones')
    op.drop_table('venue_zones')
    op.drop_index(op.f('ix_sync_events_workstation_id'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_id'), table_name='sync_events')
    op.drop_index(op.f('ix_sync_events_customer_id'), table_name='sync_events')
    op.drop_table('sync_events')
    op.drop_index(op.f('ix_operations_venue_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_principal_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_customer_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_drones_serial'), table_name='drones')
    op.drop_index(op.f('ix_drones_kit_id'), table_name='drones')
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.drop_index(op.f('ix_drones_customer_id'), table_name='drones')
    op.drop_table('drones')
    op.drop_index(op.f('ix_workstations_id'), table_name='workstations')
    op.drop_index(op.f('ix_workstations_customer_id'), table_name='workstations')
    op.drop_table('workstations')
    op.drop_index(op.f('ix_venues_id'), table_name='venues')
    op.drop_index(op.f('ix_venues_customer_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_protection_agents_id'), table_name='protection_agents')
    op.drop_index(op.f('ix_protection_agents_customer_id'), table_name='protection_agents')
    op.drop_table('protection_agents')
    op.drop_index(op.f('ix_principals_id'), table_name='principals')
    op.drop_index(op.f('ix_principals_customer_id'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_kits_serial'), table_name='kits')
    op.drop_index(op.f('ix_kits_id'), table_name='kits')
    op.drop_index(op.f('ix_kits_customer_id'), table_name='kits')
    op.drop_table('kits')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
