"""add_operators_activation_codes_dashboard_users

Revision ID: 500c9c6a021b
Revises: 467c2a8d3778
Create Date: 2026-02-28 18:10:03.108751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.database.base import UUIDType
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '500c9c6a021b'
down_revision: Union[str, None] = '467c2a8d3778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_users',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=True),
    sa.Column('supabase_uid', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_users_customer_id'), 'dashboard_users', ['customer_id'], unique=False)
    op.create_index(op.f('ix_dashboard_users_id'), 'dashboard_users', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_users_supabase_uid'), 'dashboard_users', ['supabase_uid'], unique=True)
    op.create_table('operators',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('pin_digits_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_customer_id'), 'operators', ['customer_id'], unique=False)
    op.create_index(op.f('ix_operators_id'), 'operators', ['id'], unique=False)
    op.create_table('activation_codes',
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('customer_id', UUIDType(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('claimed_by_workstation_id', UUIDType(), nullable=True),
    sa.Column('claimed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_codes_code'), 'activation_codes', ['code'], unique=True)
    op.create_index(op.f('ix_activation_codes_customer_id'), 'activation_codes', ['customer_id'], unique=False)
    op.create_index(op.f('ix_activation_codes_id'), 'activation_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activation_codes_id'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_customer_id'), table_name='activation_codes')
    op.drop_index(op.f('ix_activation_codes_code'), table_name='activation_codes')
    op.drop_table('activation_codes')
    op.drop_index(op.f('ix_operators_id'), table_name='operators')
    op.drop_index(op.f('ix_operators_customer_id'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_dashboard_users_supabase_uid'), table_name='dashboard_users')
    op.drop_index(op.f('ix_dashboard_users_id'), table_name='dashboard_users')
    op.drop_index(op.f('ix_dashboard_users_customer_id'), table_name='dashboard_users')
    op.drop_table('dashboard_users')
    # ### end Alembic commands ###
